export type ProductSponsorId =
  | "cursor"
  | "zavu"
  | "n8n"
  | "codex"
  | "yonjob"
  | "nubiwork"
  | "abaco"
  | "elevenlabs"
  | "simov"
  | "kreali"
  | "maca"
  | "weris"
  | "boxful"
  | "crafter"
  | "drop"
  | "gamesquad"
  | "searchyou"
  | "dma"
  | "netlify"
  | "wispr"
  | "fal"
  | "exa"
  | "svnet"
  | "firecrawl"
  | "esrobotica"
  | "datamcp"
  | "rcns"
  | "from021"
  | "gad-dev"
  | "mistral"
  | "supabase"
  | "ieee"
  | "ufg";

export type OnePagerSponsorLogoId = ProductSponsorId | "cursor";
