export type ProductSponsorId =
  | "n8n"
  | "codex"
  | "yonjob"
  | "nubiwork"
  | "abaco"
  | "elevenlabs"
  | "simov"
  | "kreali"
  | "weris"
  | "boxful"
  | "drop"
  | "gamesquad"
  | "searchyou"
  | "dma"
  | "netlify"
  | "wispr"
  | "fal"
  | "exa"
  | "svnet"
  | "firecrawl"
  | "datamcp"
  | "rcns";

export type OnePagerSponsorLogoId = ProductSponsorId | "cursor";
